#! /bin/bash

TL=https://www.coinigy.com/main/markets/GDAX/ETH/USD
TR=https://www.coinigy.com/main/markets/GDAX/ETH/BTC
BL=https://www.coinigy.com/main/markets/GDAX/BTC/USD
BR=https://www.coinigy.com/main/markets/BTRX/NEO/ETH

workspace="workspace 4"
browser="exec google-chrome-stable --new-window"
container=0.5
maximize=0.25

i3-msg "$workspace;kill;focus parent;kill;focus parent;kill;focus parent;kill;layout splith;"
i3-msg "$browser $TL"
sleep $container
i3-msg "$browser $TR;"
sleep $container
i3-msg "split v;$browser $BR;"
sleep $container
i3-msg "focus left;split v;$browser $BL"
xdotool key F11 && sleep $maximize && i3-msg "fullscreen toggle;focus up"
sleep $maximize
xdotool key F11 && sleep $maximize && i3-msg "fullscreen toggle;focus right"
sleep $maximize
xdotool key F11 && sleep $maximize && i3-msg "fullscreen toggle;focus down"
sleep $maximize
xdotool key F11 && sleep $maximize && i3-msg "fullscreen toggle;focus left"
xdotool key Control_L+Shift_L+f && i3-msg "focus up"
xdotool key Control_L+Shift_L+f && i3-msg "focus right"
xdotool key Control_L+Shift_L+f && i3-msg "focus down"
xdotool key Control_L+Shift_L+f && i3-msg "focus left"
