#! /bin/bash

TL=https://www.coinigy.com/main/markets/$1
TR=https://www.coinigy.com/main/markets/$2
BL=https://www.coinigy.com/main/markets/$3
BR=https://www.coinigy.com/main/markets/$4

workspace="workspace $1"
browser="exec google-chrome-stable --new-window"
container=1
maximize=0.5

i3-msg "$workspace;kill;focus parent;kill;focus parent;kill;focus parent;kill;layout splith;"
i3-msg "$browser $TL"
sleep $container
i3-msg "$browser $TR;"
sleep $container
i3-msg "split v;$browser $BR;"
sleep $container
i3-msg "focus left;split v;$browser $BL"
xdotool key F11 && sleep $maximize && i3-msg "fullscreen toggle;focus up"
sleep $maximize
xdotool key F11 && sleep $maximize && i3-msg "fullscreen toggle;focus right"
sleep $maximize
xdotool key F11 && sleep $maximize && i3-msg "fullscreen toggle;focus down"
sleep $maximize
xdotool key F11 && sleep $maximize && i3-msg "fullscreen toggle;focus left"
xdotool key Control_L+Shift_L+f && i3-msg "focus up"
xdotool key Control_L+Shift_L+f && i3-msg "focus right"
xdotool key Control_L+Shift_L+f && i3-msg "focus down"
xdotool key Control_L+Shift_L+f && i3-msg "focus left"
